<div class="custom-form">
    <form id="customForm">
        <label for="tname">Text</label>
        <input type="text" id="tname" name="text" placeholder="Input text.." required style="margin-bottom: 20px;">

        <br>

        <input name="myFile" type="file" style="margin-bottom: 20px;">

        <br>

        <input type="radio" id="errorMessage" name="message">
        <label for="errorMessage">Error Message</label >

        <br>

        <input type="radio" id="successMessage" name="message">
        <label for="successMessage"> Success Message</label>

        <br>

        <input type="submit" value="Show Message" style="margin-top: 20px;">
    </form>
</div>


<script type="text/javascript">
    require([
        "jquery"
    ], function($){
        "use strict";

        $('#customForm').submit(function (){
           $.ajax({
               type: 'POST',
               dataType: 'application/json',
               data: $(this).serialize(),
           }) ;
        });

    });
</script>
