<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/**
 * Product view template
 *
 * @see \Magento\Catalog\Block\Product\View\Description
 */
?>
<?php
$_helper = $this->helper('Magento\Catalog\Helper\Output');
$_product = $block->getProduct();
?>

<div class="product attribute overview">
    <div data-mage-init="{'attributepopup': {}}"><a id="click-info" href="#">Information</a></div>
    <div id="popup-modal">
        <?php echo $_product->getResource()->getAttribute('information')->getFrontend()->getValue($_product); ?>
    </div>
</div>
